---
# defaults file for roles/wordpress

mysql_root_pass: 'passwd'

db_name: 'wordpress'
db__pass: 'password'

php_modules:
  - php73
  - php-fpm
  - php-cli
  - php-mysqlnd
  - php-gd
  - php-ldap
  - php-odbc
  - php-pdo
  - php-pecl-memcache
  - php-pear
  - php-xml
  - php-xmlrpc
  - php-mbstring
  - php-snmp
  - php-soap
  - php-zip
  - php-opcache
  - php-imap
