---
# handlers file for roles/flask

- name: start nginx
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: restart nginx
  systemd:
    name: nginx
    state: restarted

- name: start php-fpm
  systemd:
    name: php-fpm
    state: started
    enabled: yes

- name: restart php-fpm
  systemd:
    name: php-fpm
    state: restarted

- name: restart unit
  shell: systemctl daemon-reload
  listen: unit

- name: start uwsgi.service
  systemd:
    name: uwsgi.service
    state: started
    enabled: yes
  listen: unit


