---
# defaults file for roles/flask

php_modules:
  - php73
  - php-fpm
  - php-cli
  - php-mysqlnd
  - php-gd
  - php-ldap
  - php-odbc
  - php-pdo
  - php-pecl-memcache
  - php-pear
  - php-xml
  - php-xmlrpc
  - php-mbstring
  - php-snmp
  - php-soap
  - php-zip
  - php-opcache
  - php-imap
