---
# tasks file for roles/flask

- name: Install python3 packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - gcc
    - python-pip
    - python-devel
#    - python3
#    - python3-pip 
#    - python3-devel
#    - python3-virtualenv
#    - python-setuptools

- name: Upgrade pip
  pip:
    name: pip
    state: forcereinstall

- name: Upgrade setuptools
  pip:
    name: setuptools
    state: forcereinstall

#- name: Install virtualenv
#  pip:
#    name: virtualenv
#    executable: pip3

- name: Create directory flask
  file:
    path: /var/www/flask
    state: directory
    recurse: Yes
    mode: '0755'
    owner: root
    group: root

#- name: Create environment
#  command: /usr/local/bin/virtualenv /var/www/flask/env

#- name: Install flask and gunicorn
#  pip:
#    name: "{{ item }}"
#    virtualenv: /var/www/flask/env
#  with_items:
#    - flask
#    - gunicorn

#- name: Copy config file
#  copy:
#    src: flask.conf
#    dest: /etc/nginx/conf.d/flask.conf
#  notify: restart nginx

- name: Copy python files
  copy:
    src: flask.py
    dest: /var/www/flask/flask.py
    force: Yes

#- name: Copy flask unit
#  copy:
#    src: flask.service
#    dest: /etc/systemd/system/flask.service
#  notify: unit
