---
# tasks file for roles/flask

- name: Установим epel
  yum:
    name:
    - epel-release

- name: Install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - gcc
    - python-pip
    - python-devel

- name: Upgrade pip
  shell: |
    curl https://bootstrap.pypa.io/pip/2.7/get-pip.py | python

- name: Upgrade setuptools
  pip:
    name: setuptools
    state: forcereinstall

- name: Django, -pip
  pip:
    name: [Django, uwsgi]

- name: Create directory flask
  file:
    path: /var/www/django
    state: directory
    recurse: Yes
    mode: '0755'
    owner: root
    group: root




