---
# tasks file for roles/flask

- name: Set timezone to Europe/Moscow
  timezone:
    name: Europe/Moscow

- name: Flask_nginx
  include_tasks: nginx.yml

#- name: Flask_php-fpm
#  include_tasks: php-fpm.yml

- name: Install django
  include_tasks: django.yml
