---
# tasks file for roles/react

- name: Add Nginx repository
  copy:
    src: CentOS-Nginx.repo
    dest: /etc/yum.repos.d/

- name: Install Nginx package
  yum:
    name: nginx
    state: present
  notify: start nginx
